# Generated by Django 5.1.6 on 2025-03-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_for_activate',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
