# Generated by Django 5.1.5 on 2025-03-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=15, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(blank=True, default=1, max_length=15, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
