# Generated by Django 5.1.6 on 2025-03-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_token_for_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='token_for_activate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
