# Generated by Django 5.1.5 on 2025-03-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
