# Generated by Django 5.1.5 on 2025-02-04 13:45

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientName',
            fields=[
                ('email', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='email клиента')),
                ('name', models.CharField(max_length=150, verbose_name='Фамилия Имя Отчество')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('unsubscribe', models.IntegerField(blank=True, default=None, editable=False, null=True, verbose_name='Отписка')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_mail', models.CharField(max_length=150, verbose_name='Тема письма')),
                ('text_mail', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailForSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.clientname')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_at', models.DateTimeField(auto_now_add=True, verbose_name='время рассылки')),
                ('success', models.BooleanField(verbose_name='статус операции')),
                ('response', models.CharField(max_length=250, verbose_name='ответ сервера')),
                ('email_for_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_for_send', to='mailing.emailforsend')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'ordering': ['-attempt_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='имя задачи')),
                ('start_at', models.DateTimeField(verbose_name='время начала рассылки')),
                ('end_at', models.DateTimeField(verbose_name='время завершения рассылки')),
                ('status', models.CharField(choices=[('stop', 'Остановлена'), ('end', 'Завершена'), ('created', 'Создана'), ('start', 'Запущена')], default='stop', max_length=10, verbose_name='Статус')),
                ('client_emails', models.ManyToManyField(through='mailing.EmailForSend', to='mailing.clientname')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='mailing.message', verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-start_at'],
            },
        ),
        migrations.AddField(
            model_name='emailforsend',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.task'),
        ),
    ]
