# Generated by Django 5.1.6 on 2025-03-02 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientname',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailforsend',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.clientname'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='email_for_send',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_for_send', to='mailing.emailforsend'),
        ),
        migrations.AddField(
            model_name='task',
            name='client_emails',
            field=models.ManyToManyField(related_name='tasks', through='mailing.EmailForSend', to='mailing.clientname'),
        ),
        migrations.AddField(
            model_name='task',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='mailing.message', verbose_name='Текст сообщения'),
        ),
        migrations.AddField(
            model_name='emailforsend',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.task'),
        ),
        migrations.AlterUniqueTogether(
            name='clientname',
            unique_together={('email', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='emailforsend',
            unique_together={('task', 'client')},
        ),
    ]
