# Generated by Django 5.1.5 on 2025-02-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Коментарии'),
        ),
        migrations.AlterField(
            model_name='task',
            name='client_emails',
            field=models.ManyToManyField(related_name='tasks', through='mailing.EmailForSend', to='mailing.clientname'),
        ),
    ]
