# Generated by Django 5.1.5 on 2025-01-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=None, max_length=150, verbose_name='имя задачи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientname',
            name='unsubscribe',
            field=models.IntegerField(default=None, null=True, verbose_name='Отписка'),
        ),
        migrations.AlterField(
            model_name='emailforsend',
            name='token',
            field=models.CharField(default='rki6om!26ld@0wy^xri2+_z55!0jctxq2kv3f1^h5qqa0u1sdz', max_length=50),
        ),
    ]
