# Generated by Django 5.1.5 on 2025-02-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientname',
            name='unsubscribe',
            field=models.IntegerField(default=0, editable=False, verbose_name='Отписка'),
        ),
    ]
