# Generated by Django 5.1.5 on 2025-01-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_message_options_task_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientname',
            name='unsubscribe',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Отписка'),
        ),
        migrations.AlterField(
            model_name='emailforsend',
            name='token',
            field=models.CharField(default='icndha$p6i$k3yx@q4)22gil^kj*!!r6u4wheyy76$%*24jh^j', max_length=50),
        ),
    ]
