# Generated by Django 5.1.5 on 2025-02-17 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_task_description_alter_task_client_emails'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailforsend',
            unique_together={('task', 'client')},
        ),
    ]
