# Generated by Django 5.1.5 on 2025-03-10 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='email_for_send',
        ),
        migrations.AddField(
            model_name='attempt',
            name='task_send',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mail_for_send', to='mailing.task'),
            preserve_default=False,
        ),
    ]
