# Generated by Django 5.1.5 on 2025-01-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_clientname_unsubscribe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientname',
            name='unsubscribe',
            field=models.IntegerField(blank=True, default=None, editable=False, null=True, verbose_name='Отписка'),
        ),
        migrations.AlterField(
            model_name='emailforsend',
            name='token',
            field=models.CharField(default='rag3-&f)@!rdf7wga*0$a5)h-g=)(^k4u!iz7f+-!jx3@ea0+p', max_length=50),
        ),
    ]
