# Generated by Django 5.1.6 on 2025-03-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_message_user_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время завершения рассылки'),
        ),
    ]
