# Generated by Django 5.1.5 on 2025-03-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_remove_attempt_email_for_send_attempt_task_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='len_mail',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество отправленных писем'),
        ),
    ]
