# Generated by Django 5.1.5 on 2025-01-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_clientname_unsubscribe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailforsend',
            name='token',
            field=models.CharField(default='f2_@59m24qj4(%i9$*=^)m0ej!1!qw#82$h5fga_-m7k7e0qk@', max_length=50),
        ),
    ]
