# Generated by Django 5.1.6 on 2025-03-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_task_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientname',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
