# Generated by Django 5.1.5 on 2025-01-30 18:01

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_emailforsend_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailforsend',
            name='token',
            field=models.CharField(default='li74^-n1+tymx$0%0&wp8vtd65_64#ro+)##34ab*e(3n^==xa', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='text_mail',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст mail'),
        ),
    ]
