# Generated by Django 5.1.5 on 2025-02-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_emailforsend_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailforsend',
            name='token',
            field=models.CharField(default='f8=fhry^nc@1)&z)s_3_8^+31(s@x3rp386*0zli#7qi8wn4!=', max_length=50),
        ),
    ]
