# Generated by Django 5.1.5 on 2025-02-04 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_emailforsend_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientname',
            name='id',
        ),
        migrations.AlterField(
            model_name='clientname',
            name='email',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='email клиента'),
        ),
        migrations.AlterField(
            model_name='emailforsend',
            name='token',
            field=models.CharField(default='5gp*2avua1*#ilpzkdu^33(6eg82=0&r3=lgx27f4m^0*l_g=e', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='mailing.message', verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('stop', 'Остановлена'), ('end', 'Завершена'), ('created', 'Создана'), ('start', 'Запущена')], default='stop', max_length=10, verbose_name='Статус'),
        ),
    ]
